# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Child(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, parent: int=None):  # noqa: E501
        """Child - a model defined in Swagger

        :param id: The id of this Child.  # noqa: E501
        :type id: int
        :param name: The name of this Child.  # noqa: E501
        :type name: str
        :param parent: The parent of this Child.  # noqa: E501
        :type parent: int
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'parent': int
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'parent': 'parent'
        }
        self._id = id
        self._name = name
        self._parent = parent

    @classmethod
    def from_dict(cls, dikt) -> 'Child':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Child of this Child.  # noqa: E501
        :rtype: Child
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Child.


        :return: The id of this Child.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Child.


        :param id: The id of this Child.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Child.


        :return: The name of this Child.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Child.


        :param name: The name of this Child.
        :type name: str
        """

        self._name = name

    @property
    def parent(self) -> int:
        """Gets the parent of this Child.


        :return: The parent of this Child.
        :rtype: int
        """
        return self._parent

    @parent.setter
    def parent(self, parent: int):
        """Sets the parent of this Child.


        :param parent: The parent of this Child.
        :type parent: int
        """

        self._parent = parent
