/**
 * Family API
 * Basic API Specification
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ParentsApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_ParentsApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_ParentsApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/Parent.h"
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  ParentsApi 
{
public:

    explicit ParentsApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~ParentsApi();

    /// <summary>
    /// Returns the parent with the provided id
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="pid">Parent id</param>
    pplx::task<std::shared_ptr<Parent>> getParent(
        int32_t pid
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_ParentsApi_H_ */

