version: '3'

services:
  flask-app:
    build: .
    ports:
      - "8080:8080"
    network_mode: bridge

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - .nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app
    network_mode: bridge